const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.destroy,
		C3.Behaviors.Physics,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Behaviors.Platform.Acts.SetDoubleJumpEnabled,
		C3.Behaviors.Platform.Acts.SetMaxFallSpeed,
		C3.Behaviors.Platform.Acts.SetAcceleration,
		C3.Behaviors.Platform.Acts.SetDeceleration,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.TiledBg.Exps.BBoxMidX,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareVar
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{ScrollTo: 0},
	{BoundToLayout: 0},
	{Character: 0},
	{Solid: 0},
	{Ground1: 0},
	{Platform2: 0},
	{Obstacle1: 0},
	{Keyboard: 0},
	{Spikes: 0},
	{EndGame: 0},
	{DestroyOutsideLayout: 0},
	{Physics: 0},
	{EndGameCelebration: 0},
	{Jumpthru: 0},
	{Ground2: 0},
	{Sine: 0},
	{Platform1: 0},
	{CollectibleWasGot: 0},
	{NextLevel: 0},
	{Collectible: 0},
	{Platform3: 0},
	{SPIKESV2BABY: 0},
	{LevelCounter: 0}
];

self.InstanceType = {
	Character: class extends self.ISpriteInstance {},
	Ground1: class extends self.ITiledBackgroundInstance {},
	Platform2: class extends self.ITiledBackgroundInstance {},
	Obstacle1: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	Spikes: class extends self.ITiledBackgroundInstance {},
	EndGame: class extends self.ISpriteInstance {},
	EndGameCelebration: class extends self.ISpriteInstance {},
	Ground2: class extends self.ITiledBackgroundInstance {},
	Platform1: class extends self.ITiledBackgroundInstance {},
	CollectibleWasGot: class extends self.IParticlesInstance {},
	NextLevel: class extends self.ISpriteInstance {},
	Collectible: class extends self.ISpriteInstance {},
	Platform3: class extends self.ITiledBackgroundInstance {},
	SPIKESV2BABY: class extends self.ITiledBackgroundInstance {}
}